<a href="https://colab.research.google.com/github/hugo1623/AdminPro/blob/master/Tarea01_E03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EJERCICIO 3: NUMPY**

1. Crear un vector con valores dentro del rango 10 a 29

In [1]:
import numpy as np

In [94]:
array=np.arange(10, 29)
array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28])

2. Invertir el vector

In [11]:
array[::-1]

array([28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12,
       11, 10])

3. Crear una matriz 4x4 con valores de 0 a 15

In [95]:
a = np.array([[0, 1, 2, 3], [4,5, 6, 7], [8,9, 10, 11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

4. Encontrar los índices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [93]:
x = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.where(x == 0)[0]

array([ 5,  7,  8,  9, 15])

5. Crear una matriz identidad de 8x8

In [15]:
a = np.array([[1,0,0,0,0,0,0,0], [0,1,0,0,0,0,0,0], [0,0,1,0,0,0,0,0], [0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0], [0,0,0,0,0,1,0,0], [0,0,0,0,0,0,1,0], [0,0,0,0,0,0,0,1]])
a

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
6. Crear una matriz con valores al azar con forma 6x6

In [31]:

A = np.random.rand(6,6)
A

array([[3.86423695e-01, 1.82854610e-01, 7.79495972e-02, 4.38790525e-04,
        4.64614020e-01, 9.54333444e-01],
       [1.90931717e-01, 4.71330642e-01, 3.97410148e-01, 5.78578730e-01,
        7.78049379e-01, 3.36381526e-01],
       [4.88076942e-01, 3.04617075e-01, 9.76217359e-01, 3.26623297e-01,
        2.24670735e-02, 9.22715318e-01],
       [1.65117564e-01, 5.46505180e-01, 9.10564319e-01, 1.49017486e-01,
        7.06230754e-01, 3.42796757e-01],
       [8.44143105e-01, 4.90874497e-01, 3.62603483e-01, 4.24353833e-01,
        8.52998061e-01, 5.30535401e-01],
       [2.96084347e-01, 9.25011291e-01, 2.91042610e-01, 8.53470616e-01,
        4.70756328e-01, 7.66512683e-01]])

7. Encontrar los índices de los valores mínimos y máximos de la anterior matriz

In [36]:
Min = np.amin(A)
Max =np.amax(A)

print("El valor Minimo es", Min);
print("El valor Minimo es", Max);

El valor Minimo es 0.0004387905249425561
El valor Minimo es 0.9762173590282469


In [40]:
Minimo= np.argmin(A)
Maximo= np.argmax(A)
print("El valor Minimo es", Minimo);
print("El valor Minimo es", Maximo);

El valor Minimo es 3
El valor Minimo es 14


8. Crear dos arreglos al azar A y B, verificar si son iguales

In [59]:
M = np.random.randint(1,3,5)
N = np.random.randint(1,3,5)
print("El primer Arreglo es  :", M)
print("El segundo Arreglo es :", N)

Verificar= np.allclose(M,N)
print("\n El arreglo es", Verificar)

El primer Arreglo es  : [2 1 1 2 1]
El segundo Arreglo es : [2 2 1 2 1]

 El arreglo es False


9. Escriba un programa NumPy para crear una matriz estructurada a partir del nombre del estudiante, la altura, la clase y sus tipos de datos. Ahora ordena la matriz por altura.

In [97]:
matrizx = [
    ('estudiante', (np.str_, 10)),
    ('altura', np.int32),
    ('clase', (np.str_, 10))]
  
matrizy = np.array([('Hugo', 70, 'M1'),
                ('Kyra', 75, 'M1'),
                ('Helen', 80, 'M1')],
               dtype=matrizx)

matrizy

array([('Hugo', 70, 'M1'), ('Kyra', 75, 'M1'), ('Helen', 80, 'M1')],
      dtype=[('estudiante', '<U10'), ('altura', '<i4'), ('clase', '<U10')])

10. Escriba un programa NumPy para calcular el histograma de nums contra los bins
Salida de muestra:números: [0.5 0.7 1. 1.2 1.3 2.1] bins: [0 1 2 3] Resultado: (matriz ([2, 3, 1], dtype = int64), matriz ([0, 1 , 2, 3]))

In [67]:
a = [0.5,0.7,1,1.2,1.3,2.1]
np.histogram(a, bins = [0, 1, 2, 3])
hist, bins = np.histogram(a, bins = [0, 1, 2, 3])
print (hist)   
print (bins) 

[2 3 1]
[0 1 2 3]
